static:
  problems:
    - "1. Find the sum of the multiples of 3 or 5 below 1000"
    - "2. Find the sum of the even valued Fibonacci numbers below 4 million"
    - "3. Find the largest prime factor of the number 600851475143"
    - "4. Find the largest palindrome made from the product of two 3-digit numbers"
    - "5. Find the smallest positive number that is evenly divisible by all of the numbers from 1 to 20"
    - "6. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum"
    - "7. Find the 10 001st prime number"
    - "8. Find the thirteen adjacent digits in the 1000-digit number that have the greatest product"
    - "9. Find the product of the Pythagorean triplet for which a + b + c = 1000"
    - "10. Find the sum of all the primes below two million"
    - "11. Find the greatest product of four adjacent numbers in the 20x20 grid"
    - "12. Find the first triangle number with over 500 divisors"
    - "13. Find the first ten digits of the sum of one hundred 50-digit numbers"
    - "14. Find the number under 1 million that produces the longest Collatz chain"
    - "15. Find the number of routes through a 20x20 grid"
    - "16. Find the sum of the digits of 2 ^ 1000"
    - "17. Find the number of letters used writing out the numbers 1 to 1000"
    - "18. Find the maximum path from top to bottom of the given triangle"
    - "19. Find the number of Sundays that fell on the first of the month during the 20th century"
    - "20. Find the sum of the digits in the number 100!"
    - "21. Find the sum of the amicable numbers under 10000"
    - "22. Find the sum of the name scores in the given text file"
    - "23. Find the sum of all positive integers that cannot be written as the sum of two abundant numbers"
    - "24. Find the 1,000,000th lexicographical permutation of the digits 0,1,2,3,4,5,6,7,8,9"
    - "25. Find the index of the first number in the Fibonacci sequence with 1000 digits"
    - "26. Find the denominator (< 1000) of the unit fraction with the largest recurring cycle in its decimal"
    - "27. Find the product of the co-efficients a and b for the quadratic expression that produces the maximum number of primes for consecutive n"
    - "28. Find the sum of numbers on the diagonal values in a 1001 by 1001 spiral"
    - "29. Find the number of distinct terms generated by a^b where a and b is between 2 and 100"