static:
  problems:
    - "1. Sum of the multiples of 3 or 5 below 1000"
    - "2. Sum of the even valued Fibonacci numbers below 4 million"
    - "3. Find the largest prime factor of the number 600851475143"
    - "4. Find the largest palindrome made from the product of two 3-digit numbers"
    - "5. Find the smallest positive number that is evenly divisible by all of the numbers from 1 to 20"
    - "6. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum"
    - "7. Find the 10 001st prime number"
    - "8. Find the thirteen adjacent digits in the 1000-digit number that have the greatest product"