package com.spring.euler.domain;

import com.spring.euler.solutions.*;

public enum Solutions {
    ONE                                  { @Override public String run() { return Problem1.run();  } },
    TWO                                  { @Override public String run() { return Problem2.run();  } },
    THREE                                { @Override public String run() { return Problem3.run();  } },
    FOUR                                 { @Override public String run() { return Problem4.run();  } },
    FIVE                                 { @Override public String run() { return Problem5.run();  } },
    SIX                                  { @Override public String run() { return Problem6.run();  } },
    SEVEN                                { @Override public String run() { return Problem7.run();  } },
    EIGHT                                { @Override public String run() { return Problem8.run();  } },
    NINE                                 { @Override public String run() { return Problem9.run();  } },
    TEN                                  { @Override public String run() { return Problem10.run(); } },
    ELEVEN                               { @Override public String run() { return Problem11.run(); } },
    TWELVE                               { @Override public String run() { return Problem12.run(); } },
    THIRTEEN                             { @Override public String run() { return Problem13.run(); } },
    FOURTEEN                             { @Override public String run() { return Problem14.run(); } },
    FIFTEEN                              { @Override public String run() { return Problem15.run(); } },
    SIXTEEN                              { @Override public String run() { return Problem16.run(); } },
    SEVENTEEN                            { @Override public String run() { return Problem17.run(); } },
    EIGHTEEN                             { @Override public String run() { return Problem18.run(); } },
    NINETEEN                             { @Override public String run() { return Problem19.run(); } },
    TWENTY                               { @Override public String run() { return Problem20.run(); } },
    TWENTY_ONE                           { @Override public String run() { return Problem21.run(); } },
    TWENTY_TWO                           { @Override public String run() { return Problem22.run(); } },
    TWENTY_THREE                         { @Override public String run() { return Problem23.run(); } },
    TWENTY_FOUR                          { @Override public String run() { return Problem24.run(); } },
    TWENTY_FIVE                          { @Override public String run() { return Problem25.run(); } },
    TWENTY_SIX                           { @Override public String run() { return Problem26.run(); } },
    TWENTY_SEVEN                         { @Override public String run() { return Problem27.run(); } },
    TWENTY_EIGHT                         { @Override public String run() { return Problem28.run(); } },
    TWENTY_NINE                          { @Override public String run() { return Problem29.run(); } },
    THIRTY                               { @Override public String run() { return Problem30.run(); } },
    THIRTY_ONE                           { @Override public String run() { return Problem31.run(); } },
    THIRTY_TWO                           { @Override public String run() { return Problem32.run(); } },
    THIRTY_THREE                         { @Override public String run() { return Problem33.run(); } },
    THIRTY_FOUR                          { @Override public String run() { return Problem34.run(); } },
    THIRTY_FIVE                          { @Override public String run() { return Problem35.run(); } },
    THIRTY_SIX                           { @Override public String run() { return Problem36.run(); } },
    THIRTY_SEVEN                         { @Override public String run() { return Problem37.run(); } },
    THIRTY_EIGHT                         { @Override public String run() { return Problem38.run(); } },
    THIRTY_NINE                          { @Override public String run() { return Problem39.run(); } },
    FORTY                                { @Override public String run() { return Problem40.run(); } },
    FORTY_ONE                            { @Override public String run() { return Problem41.run(); } },
    FORTY_TWO                            { @Override public String run() { return Problem42.run(); } },
    FORTY_THREE                          { @Override public String run() { return Problem43.run(); } },
    FORTY_FOUR                           { @Override public String run() { return Problem44.run(); } },
    FORTY_FIVE                           { @Override public String run() { return Problem45.run(); } },
    FORTY_SIX                            { @Override public String run() { return Problem46.run(); } },
    FORTY_SEVEN                          { @Override public String run() { return Problem47.run(); } },
    FORTY_EIGHT                          { @Override public String run() { return Problem48.run(); } },
    FORTY_NINE                           { @Override public String run() { return Problem49.run(); } },
    FIFTY                                { @Override public String run() { return Problem50.run(); } };

    public abstract String run();
}
